# Generated by Django 5.0.6 on 2024-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
    ]
