# Generated by Django 5.0.6 on 2024-06-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_user_is_active_user_is_admin_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'domain')},
        ),
    ]
