# Generated by Django 5.0.6 on 2024-06-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_internshipapplication_alter_user_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
