# Generated by Django 5.0.6 on 2024-06-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_internshipapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
